name: deploy-book

# Only run this when changes are pushed to the main branch
on:
  push:
    branches:
      - main

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3

    # Install Python
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    # Install Jupyter Book and any other dependencies
    - name: Install dependencies
      run: |
        pip install -U jupyter-book
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Build the HTML
    - name: Build the book
      run: |
        jupyter-book build .

    # Push the HTML to your gh-pages branch
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _build/html
